### ISSUE TITLE
Add key autocomplete feature to metadata search

### ISSUE THREAD

**Issue by fmwest** [gigantum/hybrid-object-store#215]
Look into adding key autocomplete feature to metadata search so that users can have available keys suggested to them.

Right now key-value pairs are stored in one string in the metadata search index for easier search queries. It's possible to implement auto-complete without changing this structure if the HOSS does some extra work on the side: search the index for records using a prefix query on the "metadata" field (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-prefix-query.html), which should return any key-value pairs that begin with the prefix text. Then the unique keys among the results can be parsed and returned to users as suggestions. The available values for those keys could also be returned and used as subsequent suggestions once the user chooses their preferred key.

If more complex behavior is desired, such as providing suggestions based on misspelled keys, the suggesters feature of the search API could be used: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-suggesters.html 

In this case there are two options:

1. update the schema for the metadata index to separate keys and values, for example using a nested field type with sub-fields key and value (https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html). This way a suggestion query can be performed on key sub-field alone, separately from the associated value. This would also require an update to the basic search query to use an expensive nested query for matching key-value pairs instead of a simple term query (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-nested-query.html)
2. create a new index to track keys purely for the purpose of suggestions. This index could also keep track of a list of values associated with each key and it could be updated alongside the main index whenever events are processed by the sync service. This index would be difficult to keep up-to-date with the key-value pairs currently existing in the main index (just because an object with a key-value pair is deleted doesn't mean that key-value pair isn't still in use by another object). But it could be treated only as suggestions and not as confirmation that a key or value exists in the main index

**Comment by dkleissa** [comment]
I'm curious - we currently aren't indexing on key name right? It probably would be useful to be able to search on that as well. Wondering if there are index updates required to do this ticket if it makes sense to add that as well.
